### ISSUE TITLE
Buble example?

### ISSUE THREAD

**Issue by pyros2097** [fuse-box/fuse-box-examples#14]
Add an example for buble transpiler. Btw is good to use it instead of babel or typescript?

**Comment by nchanged** [comment]
hi @pyros2097  
Buble doesn't transpile imports, besides typescript compiler is pretty fast, you can use it with raw javascript, take a look here http://fuse-box.org/page/configuration#usetypescriptcompiler

**Comment by pyros2097** [comment]
Yeah.. Just found that out after trying it out and hit a dead lock. But then why do you have buble it peeked my interest.

**Comment by nchanged** [comment]
So what isn't working for you?

**Comment by pyros2097** [comment]
The import, export is a hard stop for me in buble though it seems es6 is going to become real soon and we would not need transpilers anymore.
 I have used the typescript compiler before but I'm sticking to babel for now. Thanks.
