### ISSUE TITLE
Add fuse-box-typechecker in npm

### ISSUE THREAD

**Issue by fabien0102** [fuse-box/fuse-box-examples#15]
https://github.com/fuse-box/fuse-box-examples/blob/c46115ccb94719c117ef8d425eac7e7571549b0a/examples/react-typescript/package.json#L29

**Comment by nchanged** [comment]
@vegarringdal could you publish it?

**Comment by vegarringdal** [comment]
Ill try and get this done in the weekend :-)

**Comment by vegarringdal** [comment]
@fabien0102 
https://www.npmjs.com/package/fuse-box-typechecker
Fixed
