### ISSUE TITLE
[QUESTION] How can I add css files from npm packages?

### ISSUE THREAD

**Issue by shahabganji** [fuse-box/fuse-box-examples#19]
I want to use multiple css frameworks and libraries, such as bootstrap and pretty-checkbox, in my project, and I want to have their css files to be automatically bundled in my ```Fusebox.packages```, so fusebox can load those modules when required(import).

I tried ```CssResourcePlugin``` and ```CssPlugin``` but to noavail.

I have 
```ts
import 'pretty-checkbox/dist/pretty-checkbox.css'
```
in one of mt ```.ts``` files and I want fusebox to detect that and auto-bundle the specified css, however, I got error at runtime that ```pretty-checkbox``` does not exists?

What are the steps to add a third-party css file from npm packages? Is there any working example?

**BTW, I don't want to manually ```copy``` files by Sparky task runners.**

* I have such flexibility in **webpack**

**Comment by nchanged** [comment]
That means that pretty-checkbox isn’t installed. Clear the cache just in case, nuke modules folder and re-install

**Comment by shahabganji** [comment]
it sounds sth is wrong in my project, I made a simple project and everything worked just fine. Thanks
