### ISSUE TITLE
react-code-splitting is not working

### ISSUE THREAD

**Issue by misantronic** [fuse-box/fuse-box-examples#4]
When running the example `react-code-splitting` the app just works.
But the only reason it does is, the code-splitting is not happening. Only setting `experimentalFeatures = false` creates code-bundles.
Unfortunately, the whole app is broken after that:

<img width="849" alt="screen shot 2017-07-30 at 23 37 11" src="https://user-images.githubusercontent.com/6033531/28757312-2450b998-7580-11e7-8ce8-572acd49772b.png">

Which is because fuse-box tries to load a file directly.

I experianced the same issue on my own project.

**Comment by nchanged** [comment]
It's working. Run node fuse dist. I will update the documentation. Physicall code splitting doesn't work in Vanilla API. that's for development
